# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14S4c_mvj4MSaSXio5-nYBjHU8F0J8xR7
"""

!pip install catboost

import io
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

# Raw data loaded directly from your inputs into string format
train_data_string = """id,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales
row_00000,PRD-PRFP9S,14.252,Low Fat,0.0271,Frozen Foods,81.37,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1764.98
row_00001,PRD-PXXK71,7.698,Low Fat,0.072,HEALTH AND HYGIENE,42.05,STORE-YLW,35,Small,Tier_1,Standard Supermarket,342.13
row_00002,PRD-V5MOIJ,14.264,Regular,0.0421,Canned,41.35,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,378.85
row_00003,PRD-UN5Z3J,,Regular,0.0449,soft drinks,174.35,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,5595.72
row_00004,PRD-6RDQYB,10.338,Regular,0.012,meat,203.06,STORE-9RG,28,Small,Tier_2,Standard Supermarket,2375.36
row_00005,PRD-E6VA05,9.222,Low Fat,0.0405,soft drinks,31.69,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,842.75
row_00006,PRD-MHLD93,,Low Fat,0.1239,Canned,212.23,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,4512.7
row_00007,PRD-EF6Y39,10.21,Regular,0.0133,Snack Foods,142.7,STORE-HL7,23,Medium,Tier_3,Superstore,2373.55
row_00008,PRD-IAZMTU,14.054,Low Fat,0.0233,baking goods,102.71,STORE-HL7,23,Medium,Tier_3,Superstore,2037.05"""

test_data_string = """id,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format
row_00010,PRD-DH2TA3,8.755,Low Fat,0.0258,household,104.6,STORE-JOR,34,,Tier_3,Corner Shop
row_00011,PRD-ONGWUL,,Low Fat,0.073,Household,254.12,STORE-T5G,47,Small,Tier_1,Corner Shop
row_00012,PRD-UX01UP,11.007,Low Fat,0.0304,Snack Foods,234.38,STORE-OYG,25,,Tier_2,Standard Supermarket
row_00013,PRD-741NWE,9.558,Regular,0.0,baking goods,49.35,STORE-AGY,45,Large,Tier_3,Standard Supermarket
row_00014,PRD-PGW90J,13.812,Low Fat,0.0431,Dairy,52.83,STORE-YLW,35,Small,Tier_1,Standard Supermarket"""

def load_and_preprocess_data():
    # 1. Load Data from string buffers instead of files
    train = pd.read_csv(io.StringIO(train_data_string))
    test = pd.read_csv(io.StringIO(test_data_string))

    train_len = len(train)
    target = train['total_sales'].values

    train = train.drop(columns=['total_sales'])
    df = pd.concat([train, test], axis=0).reset_index(drop=True)

    # 2. Fix Inconsistent Categorical Capitalizations
    df['product_category'] = df['product_category'].astype(str).str.upper().str.strip()
    df['fat_content'] = df['fat_content'].astype(str).str.replace('LF', 'Low Fat').str.replace('low fat', 'Low Fat').str.replace('reg', 'Regular').str.strip()

    # 3. Handle Missing Values
    item_weight_map = df.groupby('product_code')['product_weight_kg'].mean()
    df['product_weight_kg'] = df['product_weight_kg'].fillna(df['product_code'].map(item_weight_map))
    df['product_weight_kg'] = df['product_weight_kg'].fillna(df['product_weight_kg'].mean())

    # Safely extract mode for store size mapping
    store_size_map = df.groupby('store_format')['store_size'].apply(lambda x: x.mode().iloc[0] if not x.mode().empty else 'Medium').to_dict()
    df['store_size'] = df['store_size'].fillna(df['store_format'].map(store_size_map))

    visibility_mean = df[df['shelf_visibility'] > 0]['shelf_visibility'].mean() if not df[df['shelf_visibility'] > 0].empty else 0.05
    df['shelf_visibility'] = df['shelf_visibility'].replace(0, visibility_mean)

    # 4. Feature Engineering
    category_price_mean = df.groupby('product_category')['product_price'].transform('mean')
    df['price_to_category_ratio'] = df['product_price'] / category_price_mean
    df['product_type_prefix'] = df['product_code'].apply(lambda x: str(x)[:3])
    df['store_size_format'] = df['store_size'].astype(str) + "_" + df['store_format'].astype(str)

    # 5. Categorical Encoding
    categorical_cols = ['fat_content', 'product_category', 'store_code', 'store_size',
                        'store_location_tier', 'store_format', 'product_type_prefix', 'store_size_format']

    for col in categorical_cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))

    X_train = df.iloc[:train_len].drop(columns=['id', 'product_code'])
    X_test = df.iloc[train_len:].drop(columns=['id', 'product_code'])
    test_ids = df.iloc[train_len:]['id'].values

    return X_train, target, X_test, test_ids

def train_and_evaluate():
    print("⏳ Preprocessing sample slices from memory...")
    X, y, X_test, test_ids = load_and_preprocess_data()

    # Since the sample split size is small, adjusted folds to 3 for structural evaluation safety
    n_splits = 3
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    oof_preds = np.zeros(len(X))
    test_preds = np.zeros(len(X_test))

    print(f"🚀 Training cross-validation ensemble loop...")
    for fold, (train_idx, val_index) in enumerate(kf.split(X, y)):
        X_train_f, y_train_f = X.iloc[train_idx], y[train_idx]
        X_val_f, y_val_f = X.iloc[val_index], y[val_index]

        model1 = RandomForestRegressor(n_estimators=50, max_depth=5, random_state=42, n_jobs=-1)
        model2 = GradientBoostingRegressor(n_estimators=50, max_depth=4, learning_rate=0.1, random_state=42)

        model1.fit(X_train_f, y_train_f)
        model2.fit(X_train_f, y_train_f)

        val_pred = (model1.predict(X_val_f) + model2.predict(X_val_f)) / 2
        oof_preds[val_index] = val_pred

        fold_test_pred = (model1.predict(X_test) + model2.predict(X_test)) / 2
        test_preds += fold_test_pred / n_splits

        fold_rmse = root_mean_squared_error(y_val_f, val_pred)
        print(f"✅ Fold {fold + 1} Validation RMSE: {fold_rmse:.4f}")

    overall_rmse = root_mean_squared_error(y, oof_preds)
    print(f"\n📊 Total Sample Cross-Validated RMSE Score: {overall_rmse:.4f}")

    submission = pd.DataFrame({
        'id': test_ids,
        'total_sales': test_preds
    })
    print("\n📦 Predicted outputs showcase for test set:")
    print(submission.to_string(index=False))

if __name__ == '__main__':
    train_and_evaluate()

import os
import io
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import root_mean_squared_error

# Import available GBDT frameworks with graceful fallbacks
import lightgbm as lgb
import xgboost as xgb

try:
    from catboost import CatBoostRegressor
    HAS_CATBOOST = True
except ModuleNotFoundError:
    HAS_CATBOOST = False

# ==========================================
# STEP 1: AUTO-GENERATE DATASETS TO DISK [2]
# ==========================================
train_raw_data = """id,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales
row_00000,PRD-PRFP9S,14.252,Low Fat,0.0271,Frozen Foods,81.37,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1764.98
row_00001,PRD-PXXK71,7.698,Low Fat,0.072,HEALTH AND HYGIENE,42.05,STORE-YLW,35,Small,Tier_1,Standard Supermarket,342.13
row_00002,PRD-V5MOIJ,14.264,Regular,0.0421,Canned,41.35,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,378.85
row_00003,PRD-UN5Z3J,,Regular,0.0449,soft drinks,174.35,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,5595.72
row_00004,PRD-6RDQYB,10.338,Regular,0.012,meat,203.06,STORE-9RG,28,Small,Tier_2,Standard Supermarket,2375.36
row_00005,PRD-E6VA05,9.222,Low Fat,0.0405,soft drinks,31.69,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,842.75
row_00006,PRD-MHLD93,,Low Fat,0.1239,Canned,212.23,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,4512.7
row_00007,PRD-EF6Y39,10.21,Regular,0.0133,Snack Foods,142.7,STORE-HL7,23,Medium,Tier_3,Superstore,2373.55
row_00008,PRD-IAZMTU,14.054,Low Fat,0.0233,baking goods,102.71,STORE-HL7,23,Medium,Tier_3,Superstore,2037.05"""

test_raw_data = """id,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format
row_00010,PRD-DH2TA3,8.755,Low Fat,0.0258,household,104.6,STORE-JOR,34,,Tier_3,Corner Shop
row_00011,PRD-ONGWUL,,Low Fat,0.073,Household,254.12,STORE-T5G,47,Small,Tier_1,Corner Shop
row_00012,PRD-UX01UP,11.007,Low Fat,0.0304,Snack Foods,234.38,STORE-OYG,25,,Tier_2,Standard Supermarket
row_00013,PRD-741NWE,9.558,Regular,0.0,baking goods,49.35,STORE-AGY,45,Large,Tier_3,Standard Supermarket
row_00014,PRD-PGW90J,13.812,Low Fat,0.0431,Dairy,52.83,STORE-YLW,35,Small,Tier_1,Standard Supermarket"""

print("📝 Writing training and testing CSV segments to storage...")
pd.read_csv(io.StringIO(train_raw_data)).to_csv('train.csv', index=False)
pd.read_csv(io.StringIO(test_raw_data)).to_csv('test.csv', index=False)


# ==========================================
# STEP 2: SCALED PIEPLINE PIPELINE INTERFACE
# ==========================================
def feature_engineering_pipeline(train_path='train.csv', test_path='test.csv'):
    train = pd.read_csv(train_path)
    test = pd.read_csv(test_path)

    train_len = len(train)
    y_train = train['total_sales'].values

    train_df = train.drop(columns=['total_sales'])
    combined_df = pd.concat([train_df, test], axis=0).reset_index(drop=True)

    # 1. Clean inconsistent syntax capitalizations [1, 2]
    combined_df['product_category'] = combined_df['product_category'].astype(str).str.upper().str.strip()
    combined_df['fat_content'] = (combined_df['fat_content']
                                  .astype(str)
                                  .str.replace('LF', 'Low Fat')
                                  .str.replace('low fat', 'Low Fat')
                                  .str.replace('reg', 'Regular')
                                  .str.strip())

    # 2. Impute product weights by code group mapping [1, 2]
    weight_lookup = combined_df.groupby('product_code')['product_weight_kg'].transform('mean')
    combined_df['product_weight_kg'] = combined_df['product_weight_kg'].fillna(weight_lookup)
    combined_df['product_weight_kg'] = combined_df['product_weight_kg'].fillna(combined_df['product_weight_kg'].mean())

    # 3. Impute missing store sizes using format trends [1, 2]
    format_size_mode = combined_df.groupby('store_format')['store_size'].transform(
        lambda x: x.mode().iloc if not x.mode().empty else 'Medium'
    )
    combined_df['store_size'] = combined_df['store_size'].fillna(format_size_mode)

    # 4. Correct structural 0.0 values in product shelf visibility [1, 2]
    valid_visibility_mean = combined_df[combined_df['shelf_visibility'] > 0]['shelf_visibility'].mean()
    combined_df['shelf_visibility'] = combined_df['shelf_visibility'].replace(0, valid_visibility_mean)

    # 5. Extract domain feature markers [1, 2]
    cat_price_mean = combined_df.groupby('product_category')['product_price'].transform('mean')
    combined_df['price_deviation_from_cat'] = combined_df['product_price'] - cat_price_mean
    combined_df['price_to_category_ratio'] = combined_df['product_price'] / cat_price_mean
    combined_df['product_class_prefix'] = combined_df['product_code'].apply(lambda x: str(x)[:3])
    combined_df['store_footprint_profile'] = combined_df['store_size'].astype(str) + "_" + combined_df['store_format'].astype(str)
    combined_df['visibility_price_index'] = combined_df['shelf_visibility'] * combined_df['product_price']

    # 6. Apply Label Encoding across categorical splits [1, 2]
    cat_encoded_fields = ['fat_content', 'product_category', 'store_code', 'store_size',
                          'store_location_tier', 'store_format', 'product_class_prefix', 'store_footprint_profile']

    for field in cat_encoded_fields:
        encoder = LabelEncoder()
        combined_df[field] = encoder.fit_transform(combined_df[field].astype(str))

    X_train = combined_df.iloc[:train_len].drop(columns=['id', 'product_code'])
    X_test = combined_df.iloc[train_len:].drop(columns=['id', 'product_code'])
    test_identifiers = combined_df.iloc[train_len:]['id'].values

    return X_train, y_train, X_test, test_identifiers

def execute_ensemble_training():
    X, y, X_test, test_ids = feature_engineering_pipeline()

    # Using 3 splits for safe CV sizing with current segment arrays
    num_folds = 3
    kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

    oof_predictions = np.zeros(len(X))
    final_test_predictions = np.zeros(len(X_test))

    print(f"📊 Training Ensemble models across {num_folds} validation folds...")

    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        X_tr, y_train_f = X.iloc[train_idx], y[train_idx]
        X_va, y_val_f = X.iloc[val_idx], y[val_idx]

        # LightGBM Regressor [1, 2]
        lgb_model = lgb.LGBMRegressor(
            n_estimators=500, max_depth=6, learning_rate=0.05,
            subsample=0.8, colsample_bytree=0.8, random_state=42 + fold, verbose=-1
        )
        lgb_model.fit(X_tr, y_train_f, eval_set=[(X_va, y_val_f)], callbacks=[lgb.early_stopping(30, verbose=False)])

        # XGBoost Regressor [1, 2]
        xgb_model = xgb.XGBRegressor(
            n_estimators=500, max_depth=5, learning_rate=0.05,
            subsample=0.8, colsample_bytree=0.8, random_state=42 + fold, verbosity=0
        )
        xgb_model.fit(X_tr, y_train_f, eval_set=[(X_va, y_val_f)], verbose=False)

        if HAS_CATBOOST:
            cb_model = CatBoostRegressor(iterations=500, depth=5, learning_rate=0.05, random_seed=42 + fold, verbose=0)
            cb_model.fit(X_tr, y_train_f, eval_set=(X_va, y_val_f), early_stopping_rounds=30)

            fold_val = (0.40 * lgb_model.predict(X_va) + 0.30 * xgb_model.predict(X_va) + 0.30 * cb_model.predict(X_va))
            fold_test = (0.40 * lgb_model.predict(X_test) + 0.30 * xgb_model.predict(X_test) + 0.30 * cb_model.predict(X_test))
        else:
            fold_val = (0.50 * lgb_model.predict(X_va) + 0.50 * xgb_model.predict(X_va))
            fold_test = (0.50 * lgb_model.predict(X_test) + 0.50 * xgb_model.predict(X_test))

        oof_predictions[val_idx] = fold_val
        final_test_predictions += fold_test / num_folds

        print(f"  -> Fold {fold + 1} Segment RMSE Evaluation: {root_mean_squared_error(y_val_f, fold_val):.4f}")

    print(f"\n🎯 Cross-Validated Pipeline Ensemble Score: {root_mean_squared_error(y, oof_predictions):.4f}")

    submission_output = pd.DataFrame({'id': test_ids, 'total_sales': final_test_predictions})
    submission_output.to_csv('dsn_mart_submission.csv', index=False)
    print("\n📦 Compiled submission format generated ('dsn_mart_submission.csv'):")
    print(submission_output.to_string(index=False))

if __name__ == '__main__':
    execute_ensemble_training()